version: "2"
services:

  consulagent:
    command: -server -bootstrap
    image: bharatht08/ccw-consul-server
    ports:
      - "8500:8500"

  registrator:
    command: -cleanup consul://consulagent:8500
    image: gliderlabs/registrator:v7
    links:
      - consulagent
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  git2consul:
    command: --endpoint consulagent --port 8500 --config-file /etc/git2consul.d/gitconsul.json
    image: bharatht08/ccw-git2consul
    restart: always
    links:
      - consulagent
